version: "3.9"

services:
  flashcard-umi-dev:
    build:
      context: flashcard-umi
      dockerfile: docker/Dockerfile.dev
    image: flashcard-umi:dev
    container_name: flashcard-umi-dev
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-dev}
    networks:
      - backend
    ports:
      - 8002:80
    volumes:
      - ~/.ssh:/root/.ssh

  flashcard-go-dev:
    build:
      context: flashcard-go
      dockerfile: docker/Dockerfile.dev
    image: flashcard-go:dev
    container_name: flashcard-go-dev
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-dev}
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:-mongodb://mongo:27017}
      REDIS: ${REDIS:?redis url is required}
      DB: ${DB:-flashcard}
      UC: ${UC:-http://user-center-go}
    volumes:
      - ~/.ssh:/root/.ssh
    networks:
      - backend
    depends_on:
      - mongo
      - redis

networks:
  backend:
    name: backend
    driver: bridge
