version: "3.9"

services:
  flashcard-umi:
    restart: "always"
    build:
      context: ./flashcard-umi
      dockerfile: docker/Dockerfile
    image: ngekaworu/flashcard-umi
    container_name: flashcard-umi
    networks:
      - frontend

  flashcard-go:
    restart: "always"
    build:
      context: ./flashcard-go
      dockerfile: docker/Dockerfile
    image: ngekaworu/flashcard-go
    container_name: flashcard-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:-mongodb://mongo:27017}
      REDIS: ${REDIS:?redis url is required}
      DB: ${DB:-flashcard}
      UC: ${UC:-http://user-center-go}
    networks:
      - backend
    depends_on:
      - mongo
      - redis

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
