version: "3.9"

services:
  flashcard-umi:
    
    build:
      context: ./flashcard-umi
      dockerfile: docker/Dockerfile
    image: ngekaworu/flashcard-umi
    container_name: flashcard-umi
    networks:
      - frontend

  flashcard-go:
    
    build:
      context: ./flashcard-go
      dockerfile: docker/Dockerfile
    image: ngekaworu/flashcard-go
    container_name: flashcard-go
    environment:
      PORT: ${PORT-80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:?mongo url is required}
      DB: ${DB:-flashcard}
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
